extends: 'eslint:recommended'

env:
  node: true

globals:
  Promise: true

rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
