# Travis CI config
# http://docs.travis-ci.com/user/languages/javascript-with-nodejs/
# https://docs.travis-ci.com/user/customizing-the-build/
# https://docs.travis-ci.com/user/migrating-from-legacy/

sudo: false
language: node_js
matrix:
  include:
    - node_js: 6
      env: DEPLOY=true

    - node_js: 5

    - node_js: 4

    - node_js: 0.12
      env: ESLINT_VER=2

before_script:
  # Install the version of ESLint that is compatible with this version of Node
  - 'if [ "$ESLINT_VER" != "" ]; then npm install eslint@$ESLINT_VER; fi'

script:
  - npm run cover
  - npm run lint

after_success:
  # send code-coverage data to Codacy
  - cat ./coverage/lcov.info | node_modules/.bin/codacy-coverage -p .

  # send code-coverage data to Coveralls
  - cat ./coverage/lcov.info | node_modules/coveralls/bin/coveralls.js

deploy:
  provider: npm
  email: ${NPM_EMAIL}
  api_key: ${NPM_API_KEY}
  on:
    tags: true
    repo: BigstickCarpet/readdir-enhanced
    branch: master
    condition: $DEPLOY = true
